spaces.store: "mongodb://admin:3dJ-b35LBuqC@OPENSHIFT_MONGODB_DB_HOST:OPENSHIFT_MONGODB_DB_PORT/spaces"
server:
  applicationConnectors:
    - type: http
      bindHost: @OPENSHIFT_DIY_IP@
      port: 8080
  adminConnectors:
    - type: http
      bindHost: @OPENSHIFT_DIY_IP@
      port: 8081
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /var/lib/openshift/56b59b0f0c1e66506b000214/app-root/logs/myapplication.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/lib/openshift/56b59b0f0c1e66506b000214/app-root/logs/myapplication-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %thread %level %logger{36} - %msg%n"